services:
  nginx:
    image: nginx:alpine
    container_name: academic-planner-nginx
    ports:
      - "32768:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_RESEND_KEY: ${AUTH_RESEND_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        OAUTH_PRIVATE_KEY: ${OAUTH_PRIVATE_KEY}
    container_name: academic-planner
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - AUTH_URL=https://planner.sambhav-surana.online
    restart: unless-stopped
