services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    container_name: academic-planner
    ports:
      - "32768:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - AUTH_URL=https://planner.sambhav-surana.online
    restart: unless-stopped
